# Generated by Django 4.1.3 on 2022-12-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=25)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=122)),
                ("address2", models.CharField(max_length=122)),
                ("country", models.CharField(max_length=20)),
                ("zip", models.CharField(max_length=6)),
                ("sameAddress", models.BooleanField()),
                ("credit", models.BooleanField()),
                ("debit", models.BooleanField()),
                ("ccName", models.CharField(max_length=122)),
                ("ccNumber", models.CharField(max_length=16)),
                ("ccExpiration", models.CharField(max_length=7)),
                ("ccCvv", models.CharField(max_length=3)),
                ("date", models.DateField()),
            ],
        ),
    ]
