# Generated by Django 4.1.3 on 2022-12-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipping",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="shipping",
            name="debit",
        ),
        migrations.RemoveField(
            model_name="shipping",
            name="sameAddress",
        ),
    ]
